In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]

In [5]:
my_list

[1, 2, 3]

In [9]:
arr = np.array(my_list)

In [10]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [12]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [20]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [22]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [29]:
np.linspace(0,50,5)

array([  0. ,  12.5,  25. ,  37.5,  50. ])

In [30]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [33]:
np.random.rand(5)

array([ 0.41045288,  0.9427315 ,  0.16454614,  0.0865444 ,  0.70254405])

In [34]:
np.random.rand(5,5)

array([[ 0.97387727,  0.87902147,  0.12443006,  0.79811131,  0.42861289],
       [ 0.91293253,  0.38698218,  0.63181402,  0.17703125,  0.88136841],
       [ 0.51423834,  0.06658817,  0.95956387,  0.65411619,  0.39294964],
       [ 0.81651841,  0.86672125,  0.03961052,  0.88899217,  0.04626494],
       [ 0.62235096,  0.30380749,  0.60492031,  0.20217211,  0.98048689]])

In [35]:
np.random.randn(2)

array([-1.38346759, -0.4598734 ])

In [40]:
np.random.randint(1,100,10)

array([96, 95, 52, 78, 31,  7, 71, 17, 53, 45])

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
ranarr=np.random.randint(0,50,10)

In [53]:
ranarr

array([28, 23, 25, 12, 32, 41, 41,  7,  4, 31])

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranarr.max()

41

In [55]:
ranarr.min()

4

In [56]:
ranarr

array([28, 23, 25, 12, 32, 41, 41,  7,  4, 31])

In [57]:
ranarr.argmax()

5

In [58]:
ranarr.argmin()

8

In [59]:
arr.shape

(25,)

In [60]:
arr = arr.reshape(5,5)

In [61]:
arr.shape

(5, 5)

In [62]:
arr.dtype

dtype('int32')

In [63]:
from numpy.random import randint

In [69]:
randint(3,8)

4

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr[7]

7

In [82]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [81]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [83]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [85]:
arr[0:5]=100

In [86]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [87]:
arr=np.arange(0,11)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
slice_of_arr = arr[0:6]

In [91]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [92]:
slice_of_arr[:]=99

In [93]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [94]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [95]:
arr_copy = arr.copy()

In [96]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [97]:
arr_copy[:]=100

In [98]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [99]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [105]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [106]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [107]:
arr_2d[0][0]

5

In [108]:
arr_2d[2][1]

40

In [124]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

array([[ 5, 10, 15]])

array([[20, 25, 30],
       [35, 40, 45]])